In [2]:
import pandas as pd

In [3]:
columns = ["Name", "Age", "Height"]
data = [
    ["Allen", 22, 175],  # the 0-th row of data
    ["Ted", 25, 180],  # the 1-st row of data
]

In [4]:
df = pd.DataFrame(
    columns=columns,
    data=data,
)

df

    Name  Age  Height
0  Allen   22     175
1    Ted   25     180

In [5]:
df.loc[2] = ["Jack", 28, 177]
df

    Name  Age  Height
0  Allen   22     175
1    Ted   25     180
2   Jack   28     177

In [6]:
df["Weight"] = [75, 80, 77]

df

    Name  Age  Height  Weight
0  Allen   22     175      75
1    Ted   25     180      80
2   Jack   28     177      77

In [7]:
df["Weight"] = 77

df

    Name  Age  Height  Weight
0  Allen   22     175      77
1    Ted   25     180      77
2   Jack   28     177      77

In [8]:
df.drop("Weight", axis=1)

    Name  Age  Height
0  Allen   22     175
1    Ted   25     180
2   Jack   28     177

In [9]:
df = df.drop("Weight", axis=1)
df

    Name  Age  Height
0  Allen   22     175
1    Ted   25     180
2   Jack   28     177

In [10]:
df.drop(2)

    Name  Age  Height
0  Allen   22     175
1    Ted   25     180

In [11]:
df

    Name  Age  Height
0  Allen   22     175
1    Ted   25     180
2   Jack   28     177

In [12]:
df = df.drop(2)
df

    Name  Age  Height
0  Allen   22     175
1    Ted   25     180

In [13]:
df.loc[0, "Age"]

np.int64(22)

In [14]:
df.loc[0, "Age"] = 25
df

    Name  Age  Height
0  Allen   25     175
1    Ted   25     180

In [15]:
df["Name"]

0    Allen
1      Ted
Name: Name, dtype: object

In [16]:
type(df)

pandas.core.frame.DataFrame

In [17]:
type(df["Name"])

pandas.core.series.Series