In [1]:
import pandas as pd

file_path = "holding.parquet"

In [2]:
df = pd.read_parquet(file_path)
df

,portno,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val,security_name,cusip
0,2998623,2020/11/30,1,2021/01/08,2.55,7078982.0,3.103426e+08,GENERAL MOTORS CO,37045V10
1,2998623,2020/11/30,2,2021/01/08,1.98,3087680.0,2.412404e+08,COGNIZANT TECHNOLOGY SOLS CORP,19244610
2,2998623,2020/11/30,3,2021/01/08,1.89,3714760.0,2.296836e+08,MORGAN STANLEY DEAN WITTER & CO,61744644
3,2998623,2020/11/30,4,2021/01/08,1.75,2815186.0,2.132503e+08,PHILIP MORRIS INTERNATIONAL INC,71817210
4,2998623,2020/11/30,5,2021/01/08,1.65,5248941.0,2.011394e+08,CORTEVA INC,22052L10
...,...,...,...,...,...,...,...,...,...
13461477,3157350,2021/11/30,428,2021/12/21,0.11,25000.0,2.229475e+04,Bausch Health Companies Inc 5% 30-JAN-2028,071734AH
13461478,3157350,2021/11/30,429,2021/12/21,0.11,25000.0,2.148050e+04,Bausch Health Companies Inc 5.25% 30-JAN-2030,071734AJ
13461479,3157350,2021/11/30,429,2021/12/21,0.11,25000.0,2.148400e+04,Bausch Health Companies Inc 5% 15-FEB-2029,071734AM
13461480,3157350,2021/11/30,431,2021/12/21,0.10,25000.0,1.918738e+04,Endo DAC 6% 30-JUN-2028,29273DAC
13461481,3157350,2021/11/30,432,2021/12/21,0.08,25000.0,1.497188e+04,PBF Holding Company LLC 6% 15-FEB-2028,69318FAJ

In [ ]:
"""
select
    distinct(portno),
    count(distinct(portno))
from holding;
"""
df["portno"].unique()

array(['2998623', '2998638', '2998809', ..., '315724e', '3157332',
       '3157350'], shape=(9453,), dtype=object)

In [4]:
df["security_name"].unique()

array(['GENERAL MOTORS CO', 'COGNIZANT TECHNOLOGY SOLS CORP',
       'MORGAN STANLEY DEAN WITTER & CO', ...,
       'AMERICREDIT AUTOMOBILE RECEIVABLES TRUST 212 A3 SEQ FIX .34% 18-DEC-2026',
       'HYUNDAI AUTO RECEIVABLES TRUST 20C A4 FIX .49% 16-NOV-2026',
       'COMM MORTGAGE TRUST 15CC26 D SEQ VAR 3.4782% 13-OCT-2048'],
      shape=(342685,), dtype=object)

In [5]:
df["cusip"].unique()

array(['37045V10', '19244610', '61744644', ..., '98163EAE', '03066RAC',
       '44891RAD'], shape=(257261,), dtype=object)

In [6]:
df.sort_values("security_name")

,portno,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val,security_name,cusip
13167275,3082602,2021/11/30,754,2021/12/21,0.03,50900.0,405693.78,&Do Holdings Co Ltd ORD,J2336210
11793139,3062403,2021/10/31,3452,2021/11/19,0.00,2600.0,21602.32,&Do Holdings Co Ltd ORD,J2336210
10555794,3062403,2021/09/30,3398,2021/10/21,0.00,2600.0,23756.55,&Do Holdings Co Ltd ORD,J2336210
4933590,315154b,2021/03/31,572,2021/05/10,0.03,1495000.0,1495000.00,.14% 01-JUL-2021,83706TAK
2764685,3062439,2021/02/28,3203,2021/03/23,0.00,25000.0,25014.61,.2% 15-DEC-2022,3134GXGQ
...,...,...,...,...,...,...,...,...,...
9757413,3152952,2021/08/31,490,2021/09/22,0.04,1755.0,79060.21,voestalpine AG ORD,A9101Y10
11288658,3082020,2021/09/30,46,2021/11/05,0.87,16933.0,625482.82,voestalpine AG ORD,A9101Y10
5769218,314472f,2021/04/30,972,2021/06/07,0.00,607.0,26336.31,voestalpine AG ORD,A9101Y10
5215217,3094215,2021/04/30,179,2021/05/24,0.08,162.0,7040.07,voestalpine AG ORD,A9101Y10
9322548,315180f,2021/08/31,184,2021/09/07,0.19,632.0,28648.09,voestalpine AG ORD,A9101Y10

In [7]:
df.groupby(["portno", "report_dt"])["percent_tna"].sum()

portno   report_dt
2998623  2020/11/30     99.79
         2020/12/31     99.20
         2021/03/31     99.96
         2021/04/30     99.93
         2021/06/30     99.78
                        ...
3157308  2021/11/30    100.23
315732c  2021/11/30    100.12
3157332  2021/11/30     99.94
315733b  2021/11/30     99.73
3157350  2021/11/30     99.55
Name: percent_tna, Length: 59339, dtype: float64

In [8]:
df.groupby(["portno", "eff_dt"])["percent_tna"].sum()

portno   eff_dt
2998623  2021/01/08     99.79
         2021/02/05     99.20
         2021/05/10     99.96
         2021/06/07     99.93
         2021/08/09     99.78
                        ...
3157308  2021/12/07    100.23
315732c  2021/12/07    100.12
3157332  2021/12/21     99.94
315733b  2021/12/07     99.73
3157350  2021/12/21     99.55
Name: percent_tna, Length: 59339, dtype: float64

In [9]:
df[
    df["portno"].isin(["2998623", "3157308", "315732c"])
]

,portno,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val,security_name,cusip
0,2998623,2020/11/30,1,2021/01/08,2.55,7078982.0,3.103426e+08,GENERAL MOTORS CO,37045V10
1,2998623,2020/11/30,2,2021/01/08,1.98,3087680.0,2.412404e+08,COGNIZANT TECHNOLOGY SOLS CORP,19244610
2,2998623,2020/11/30,3,2021/01/08,1.89,3714760.0,2.296836e+08,MORGAN STANLEY DEAN WITTER & CO,61744644
3,2998623,2020/11/30,4,2021/01/08,1.75,2815186.0,2.132503e+08,PHILIP MORRIS INTERNATIONAL INC,71817210
4,2998623,2020/11/30,5,2021/01/08,1.65,5248941.0,2.011394e+08,CORTEVA INC,22052L10
...,...,...,...,...,...,...,...,...,...
12944655,315732c,2021/11/30,28,2021/12/07,1.36,3657.0,3.916647e+04,CANOPY GROWTH CORP,13803510
12944656,315732c,2021/11/30,29,2021/12/07,1.34,5175.0,3.881250e+04,INTERCURE LTD,M549GJ11
12944657,315732c,2021/11/30,30,2021/12/07,1.34,7797.0,3.867312e+04,CLEVER LEAVES HOLDINGS INC,18676010
12944658,315732c,2021/11/30,31,2021/12/07,1.13,27117.0,3.254040e+04,GREENLANE HOLDINGS INC,39533010
12944659,315732c,2021/11/30,33,2021/12/07,-26.63,-769540.0,-7.695404e+05,USD Cash,None

In [11]:
df.groupby(["portno", "eff_dt"], as_index=False)["percent_tna"].sum()

        portno      eff_dt  percent_tna
0      2998623  2021/01/08        99.79
1      2998623  2021/02/05        99.20
2      2998623  2021/05/10        99.96
3      2998623  2021/06/07        99.93
4      2998623  2021/08/09        99.78
...        ...         ...          ...
59334  3157308  2021/12/07       100.23
59335  315732c  2021/12/07       100.12
59336  3157332  2021/12/21        99.94
59337  315733b  2021/12/07        99.73
59338  3157350  2021/12/21        99.55

[59339 rows x 3 columns]

In [16]:
df.groupby(["portno", "eff_dt"], as_index=False).agg(
    percent_sum=("percent_tna", "sum"),
    percent_mean=("percent_tna", "mean"),
    percent_std=("percent_tna", "std"),
    percent_max=("percent_tna", "max"),
    percent_min=("percent_tna", "min"),
)

,portno,eff_dt,percent_sum,percent_mean,percent_std,percent_max,percent_min
0,2998623,2021/01/08,99.79,0.284302,0.436449,2.55,-0.34
1,2998623,2021/02/05,99.20,0.284241,0.441951,2.30,-0.33
2,2998623,2021/05/10,99.96,0.287241,0.488893,3.14,-0.30
3,2998623,2021/06/07,99.93,0.288815,0.483873,3.34,-0.29
4,2998623,2021/08/09,99.78,0.285086,0.484353,4.04,-0.28
...,...,...,...,...,...,...,...
59334,3157308,2021/12/07,100.23,0.415892,0.925469,11.28,0.00
59335,315732c,2021/12/07,100.12,3.128750,6.030084,12.40,-26.63
59336,3157332,2021/12/21,99.94,0.197510,0.031781,0.32,-0.05
59337,315733b,2021/12/07,99.73,6.233125,2.035465,8.04,0.18
59338,3157350,2021/12/21,99.55,0.232593,0.203393,2.80,0.08

In [17]:
df.head()

,portno,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val,security_name,cusip
0,2998623,2020/11/30,1,2021/01/08,2.55,7078982.0,3.103426e+08,GENERAL MOTORS CO,37045V10
1,2998623,2020/11/30,2,2021/01/08,1.98,3087680.0,2.412404e+08,COGNIZANT TECHNOLOGY SOLS CORP,19244610
2,2998623,2020/11/30,3,2021/01/08,1.89,3714760.0,2.296836e+08,MORGAN STANLEY DEAN WITTER & CO,61744644
3,2998623,2020/11/30,4,2021/01/08,1.75,2815186.0,2.132503e+08,PHILIP MORRIS INTERNATIONAL INC,71817210
4,2998623,2020/11/30,5,2021/01/08,1.65,5248941.0,2.011394e+08,CORTEVA INC,22052L10

In [18]:
df.head(3)

,portno,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val,security_name,cusip
0,2998623,2020/11/30,1,2021/01/08,2.55,7078982.0,3.103426e+08,GENERAL MOTORS CO,37045V10
1,2998623,2020/11/30,2,2021/01/08,1.98,3087680.0,2.412404e+08,COGNIZANT TECHNOLOGY SOLS CORP,19244610
2,2998623,2020/11/30,3,2021/01/08,1.89,3714760.0,2.296836e+08,MORGAN STANLEY DEAN WITTER & CO,61744644

In [ ]:
df.tail()

,portno,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val,security_name,cusip
13461477,3157350,2021/11/30,428,2021/12/21,0.11,25000.0,22294.75,Bausch Health Companies Inc 5% 30-JAN-2028,071734AH
13461478,3157350,2021/11/30,429,2021/12/21,0.11,25000.0,21480.50,Bausch Health Companies Inc 5.25% 30-JAN-2030,071734AJ
13461479,3157350,2021/11/30,429,2021/12/21,0.11,25000.0,21484.00,Bausch Health Companies Inc 5% 15-FEB-2029,071734AM
13461480,3157350,2021/11/30,431,2021/12/21,0.10,25000.0,19187.38,Endo DAC 6% 30-JUN-2028,29273DAC
13461481,3157350,2021/11/30,432,2021/12/21,0.08,25000.0,14971.88,PBF Holding Company LLC 6% 15-FEB-2028,69318FAJ

In [20]:
df[5:10]

,portno,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val,security_name,cusip
5,2998623,2020/11/30,6,2021/01/08,1.64,866386.0,1.997713e+08,GOLDMAN SACHS GROUP INC,38141G10
6,2998623,2020/11/30,7,2021/01/08,1.63,2194727.0,1.976352e+08,C S X CORP,12640810
7,2998623,2020/11/30,8,2021/01/08,1.60,5045923.0,1.939653e+08,AMERICAN INTERNATIONAL GROUP INC,02687478
8,2998623,2020/11/30,9,2021/01/08,1.59,1403360.0,1.937619e+08,P N C FINANCIAL SERVICES GRP INC,69347510
9,2998623,2020/11/30,10,2021/01/08,1.54,3065766.0,1.874409e+08,C B R E GROUP INC,12504L10

In [22]:
df.loc[5:10, "portno":"security_rank"]

     portno   report_dt  security_rank
5   2998623  2020/11/30              6
6   2998623  2020/11/30              7
7   2998623  2020/11/30              8
8   2998623  2020/11/30              9
9   2998623  2020/11/30             10
10  2998623  2020/11/30             11

In [23]:
df.loc[5:10, ["portno", "report_dt", "security_rank"]]

     portno   report_dt  security_rank
5   2998623  2020/11/30              6
6   2998623  2020/11/30              7
7   2998623  2020/11/30              8
8   2998623  2020/11/30              9
9   2998623  2020/11/30             10
10  2998623  2020/11/30             11

In [24]:
df.loc[[5, 6, 7, 8, 9, 10], ["portno", "report_dt", "security_rank"]]

     portno   report_dt  security_rank
5   2998623  2020/11/30              6
6   2998623  2020/11/30              7
7   2998623  2020/11/30              8
8   2998623  2020/11/30              9
9   2998623  2020/11/30             10
10  2998623  2020/11/30             11

In [26]:
df.iloc[[5, 6, 7, 8, 9, 10], [1, 3, 5]]

     report_dt      eff_dt   nbr_shares
5   2020/11/30  2021/01/08     866386.0
6   2020/11/30  2021/01/08    2194727.0
7   2020/11/30  2021/01/08    5045923.0
8   2020/11/30  2021/01/08    1403360.0
9   2020/11/30  2021/01/08    3065766.0
10  2020/11/30  2021/01/08  186854700.0

In [27]:
df.columns

Index(['portno', 'report_dt', 'security_rank', 'eff_dt', 'percent_tna',
       'nbr_shares', 'market_val', 'security_name', 'cusip'],
      dtype='object')

In [28]:
df.dtypes

portno            object
report_dt         object
security_rank      int64
eff_dt            object
percent_tna      float64
nbr_shares       float64
market_val       float64
security_name     object
cusip             object
dtype: object

In [30]:
df.describe()

       security_rank   percent_tna    nbr_shares    market_val
count   1.346148e+07  1.346148e+07  1.346148e+07  1.346148e+07
mean    5.865976e+02  4.404682e-01  2.438436e+07  1.137428e+07
std     8.539445e+02  2.125681e+00  6.523191e+09  1.651424e+08
min     1.000000e+00 -2.489000e+02 -1.027540e+12 -6.520285e+09
25%     8.200000e+01  2.000000e-02  5.744000e+03  1.153754e+05
50%     2.750000e+02  8.000000e-02  5.249300e+04  6.464532e+05
75%     7.270000e+02  3.100000e-01  4.488590e+05  3.176073e+06
max     8.716000e+03  3.028200e+02  6.667220e+12  7.118158e+10