In [1]:
import pandas as pd

file_path = "data_with_nan.csv"

df = pd.read_csv(file_path)

df

    col1  col2 col3
0  test1  13.0  NaN
1  test2  44.0  aaa
2  test3   NaN  NaN
3    NaN   NaN  NaN
4  test5   NaN  bbb
5    NaN   NaN  NaN

In [2]:
type(None)

NoneType

In [3]:
df["col2"][2]

np.float64(nan)

In [4]:
type(df["col2"][2])

numpy.float64

In [5]:
df["col2"].mean()

np.float64(28.5)

In [6]:
df["col2"].fillna(0)

0    13.0
1    44.0
2     0.0
3     0.0
4     0.0
5     0.0
Name: col2, dtype: float64

In [7]:
df["col2"].fillna(0).mean()

np.float64(9.5)

In [8]:
df["col3"].isna()

0     True
1    False
2     True
3     True
4    False
5     True
Name: col3, dtype: bool

In [9]:
df[
    df["col3"].isna()
]

    col1  col2 col3
0  test1  13.0  NaN
2  test3   NaN  NaN
3    NaN   NaN  NaN
5    NaN   NaN  NaN

In [10]:
df[
    ~(df["col3"].isna())
]

    col1  col2 col3
1  test2  44.0  aaa
4  test5   NaN  bbb

In [11]:
df[
    df["col3"].notna()
]

    col1  col2 col3
1  test2  44.0  aaa
4  test5   NaN  bbb

In [13]:
df

    col1  col2 col3
0  test1  13.0  NaN
1  test2  44.0  aaa
2  test3   NaN  NaN
3    NaN   NaN  NaN
4  test5   NaN  bbb
5    NaN   NaN  NaN

In [12]:
df.dropna()

    col1  col2 col3
1  test2  44.0  aaa

In [14]:
df.dropna(thresh=1)

    col1  col2 col3
0  test1  13.0  NaN
1  test2  44.0  aaa
2  test3   NaN  NaN
4  test5   NaN  bbb

In [16]:
df["col1"].ffill()

0    test1
1    test2
2    test3
3    test3
4    test5
5    test5
Name: col1, dtype: object

In [17]:
df["col1"].bfill()

0    test1
1    test2
2    test3
3    test5
4    test5
5      NaN
Name: col1, dtype: object