In [3]:
import pandas as pd

file_path = "dtype_sample.csv"

df = pd.read_csv(file_path)

df

,Name,Experience,Age,Department,DepartmentID,CreatedDatetime,CreatedDatetimeTZ,Remote,OnBoard,Intern
0,John Doe,10.0,35,Engineering,1,2023-04-05T14:30,2023-04-05T14:30+08:00,True,V,0
1,Jane Smith,NaN,29,Marketing,2,2023-02-28T08:15,2023-02-28T08:15+08:00,False,X,0
2,Emily Davis,2.0,27,Product,3,2023-03-15T12:45,2023-03-15T12:45+08:00,True,V,0
3,Mark Evans,5.0,30,Sales,4,2023-01-13T09:00,2023-01-13T09:00+08:00,False,V,1

In [4]:
df.dtypes

Name                  object
Experience           float64
Age                    int64
Department            object
DepartmentID           int64
CreatedDatetime       object
CreatedDatetimeTZ     object
Remote                  bool
OnBoard               object
Intern                 int64
dtype: object

In [9]:
dtype = {
    "DepartmentID": str,
    "Remote": bool,
    "Intern": bool,
}

df = pd.read_csv(file_path, dtype=dtype)

df

,Name,Experience,Age,Department,DepartmentID,CreatedDatetime,CreatedDatetimeTZ,Remote,OnBoard,Intern
0,John Doe,10.0,35,Engineering,001,2023-04-05T14:30,2023-04-05T14:30+08:00,True,V,False
1,Jane Smith,NaN,29,Marketing,002,2023-02-28T08:15,2023-02-28T08:15+08:00,False,X,False
2,Emily Davis,2.0,27,Product,003,2023-03-15T12:45,2023-03-15T12:45+08:00,True,V,False
3,Mark Evans,5.0,30,Sales,004,2023-01-32T09:00,2023-01-13T09:00+08:00,False,V,True

In [11]:
pd.to_datetime(df["CreatedDatetime"], errors="coerce")

0   2023-04-05 14:30:00
1   2023-02-28 08:15:00
2   2023-03-15 12:45:00
3                   NaT
Name: CreatedDatetime, dtype: datetime64[ns]

In [13]:
df["OnBoard"].apply(lambda x: True if x.upper() == "V" else False)

0     True
1    False
2     True
3     True
Name: OnBoard, dtype: bool

In [14]:
import numpy as np

In [15]:
np.where(
    df["OnBoard"].str.upper() == "V",
    True,
    False,
)

array([ True, False,  True,  True])