In [1]:
import pandas as pd

staff_detail_different_col_path = "staff_detail_different_col.csv"
staff_detail_path = "staff_detail.csv"
staff_samecol_path = "staff_samecol.csv"
staff_path = "staff.csv"

staff_detail_different_col_df = pd.read_csv(staff_detail_different_col_path)
staff_detail_df = pd.read_csv(staff_detail_path)
staff_samecol_df = pd.read_csv(staff_samecol_path)
staff_df = pd.read_csv(staff_path)

In [2]:
import duckdb

con = duckdb.connect()

# 讀 parquet 檔
df = con.execute("""
    SELECT *
    FROM 'staff_df'
""").fetchdf()

df

   ID   Name  DeptId  Age Gender  Salary
0   1   Mike       2   45      M   60000
1   2   Judy       2   30      F   48000
2   3  Allen       1   22      M   50000
3   4    Tom       2   47      M   47000
4   5   Jack       3   36      M   52000
5   6   Abby       2   24      F   45000
6   7  Trump       1   80      M   80000
7   8  Marry       3   29      F   87000

In [3]:
globals()

{'__name__': '__main__',
 '__doc__': 'Automatically created module for IPython interactive environment',
 '__package__': None,
 '__loader__': None,
 '__spec__': None,
 '__builtin__': <module 'builtins' (built-in)>,
 '__builtins__': <module 'builtins' (built-in)>,
 '_ih': ['',
  'import pandas as pd\n\nstaff_detail_different_col_path = "staff_detail_different_col.csv"\nstaff_detail_path = "staff_detail.csv"\nstaff_samecol_path = "staff_samecol.csv"\nstaff_path = "staff.csv"\n\nstaff_detail_different_col_df = pd.read_csv(staff_detail_different_col_path)\nstaff_detail_df = pd.read_csv(staff_detail_path)\nstaff_samecol_df = pd.read_csv(staff_samecol_path)\nstaff_df = pd.read_csv(staff_path)',
  'import duckdb\n\ncon = duckdb.connect()\n\n# 讀 parquet 檔\ndf = con.execute("""\n    SELECT *\n    FROM \'staff_df\'\n""").fetchdf()\n\ndf',
  'globals()'],
 '_oh': {2:    ID   Name  DeptId  Age Gender  Salary
  0   1   Mike       2   45      M   60000
  1   2   Judy       2   30      F   48000
  2   3  Allen       1   22      M   50000
  3   4    Tom       2   47      M   47000
  4   5   Jack       3   36      M   52000
  5   6   Abby       2   24      F   45000
  6   7  Trump       1   80      M   80000
  7   8  Marry       3   29      F   87000},
 '_dh': [PosixPath('/Users/uuboy.scy/side-project/tibame/tjr104/data-pipeline')],
 'In': ['',
  'import pandas as pd\n\nstaff_detail_different_col_path = "staff_detail_different_col.csv"\nstaff_detail_path = "staff_detail.csv"\nstaff_samecol_path = "staff_samecol.csv"\nstaff_path = "staff.csv"\n\nstaff_detail_different_col_df = pd.read_csv(staff_detail_different_col_path)\nstaff_detail_df = pd.read_csv(staff_detail_path)\nstaff_samecol_df = pd.read_csv(staff_samecol_path)\nstaff_df = pd.read_csv(staff_path)',
  'import duckdb\n\ncon = duckdb.connect()\n\n# 讀 parquet 檔\ndf = con.execute("""\n    SELECT *\n    FROM \'staff_df\'\n""").fetchdf()\n\ndf',
  'globals()'],
 'Out': {2:    ID   Name  DeptId  Age Gender  Salary
  0   1   Mike       2   45      M   60000
  1   2   Judy       2   30      F   48000
  2   3  Allen       1   22      M   50000
  3   4    Tom       2   47      M   47000
  4   5   Jack       3   36      M   52000
  5   6   Abby       2   24      F   45000
  6   7  Trump       1   80      M   80000
  7   8  Marry       3   29      F   87000},
 'get_ipython': <bound method InteractiveShell.get_ipython of <ipykernel.zmqshell.ZMQInteractiveShell object at 0x108bbd130>>,
 'exit': <IPython.core.autocall.ZMQExitAutocall at 0x1080ef080>,
 'quit': <IPython.core.autocall.ZMQExitAutocall at 0x1080ef080>,
 'open': <function _io.open(file, mode='r', buffering=-1, encoding=None, errors=None, newline=None, closefd=True, opener=None)>,
 '_':    ID   Name  DeptId  Age Gender  Salary
 0   1   Mike       2   45      M   60000
 1   2   Judy       2   30      F   48000
 2   3  Allen       1   22      M   50000
 3   4    Tom       2   47      M   47000
 4   5   Jack       3   36      M   52000
 5   6   Abby       2   24      F   45000
 6   7  Trump       1   80      M   80000
 7   8  Marry       3   29      F   87000,
 '__': '',
 '___': '',
 '__vsc_ipynb_file__': '/Users/uuboy.scy/side-project/tibame/tjr104/data-pipeline/10_duckdb.ipynb',
 '_i': 'import duckdb\n\ncon = duckdb.connect()\n\n# 讀 parquet 檔\ndf = con.execute("""\n    SELECT *\n    FROM \'staff_df\'\n""").fetchdf()\n\ndf',
 '_ii': 'import pandas as pd\n\nstaff_detail_different_col_path = "staff_detail_different_col.csv"\nstaff_detail_path = "staff_detail.csv"\nstaff_samecol_path = "staff_samecol.csv"\nstaff_path = "staff.csv"\n\nstaff_detail_different_col_df = pd.read_csv(staff_detail_different_col_path)\nstaff_detail_df = pd.read_csv(staff_detail_path)\nstaff_samecol_df = pd.read_csv(staff_samecol_path)\nstaff_df = pd.read_csv(staff_path)',
 '_iii': '',
 '_i1': 'import pandas as pd\n\nstaff_detail_different_col_path = "staff_detail_different_col.csv"\nstaff_detail_path = "staff_detail.csv"\nstaff_samecol_path = "staff_samecol.csv"\nstaff_path = "staff.csv"\n\nstaff_detail_different_col_df = pd.read_csv(staff_detail_different_col_path)\nstaff_detail_df = pd.read_csv(staff_detail_path)\nstaff_samecol_df = pd.read_csv(staff_samecol_path)\nstaff_df = pd.read_csv(staff_path)',
 'pd': <module 'pandas' from '/Users/uuboy.scy/Library/Caches/pypoetry/virtualenvs/data-pipeline-fKJzP9fV-py3.12/lib/python3.12/site-packages/pandas/__init__.py'>,
 'staff_detail_different_col_path': 'staff_detail_different_col.csv',
 'staff_detail_path': 'staff_detail.csv',
 'staff_samecol_path': 'staff_samecol.csv',
 'staff_path': 'staff.csv',
 'staff_detail_different_col_df':     EmpNum Level  UpdateDate
 0        1     A  2019-08-09
 1        1     S  2020-12-08
 2        2     A  2021-05-30
 3        3     A  2018-03-26
 4        3     S  2020-12-08
 5        4     A  2022-05-02
 6        5     A  2019-11-05
 7        5     S  2022-04-25
 8        6     A  2022-03-03
 9        7     A  2017-03-29
 10       7     S  2018-05-02
 11       7     M  2021-09-01
 12       8     A  2018-11-26
 13       8     S  2020-03-15
 14       8     M  2022-05-03,
 'staff_detail_df':     ID Level  UpdateDate
 0    1     A  2019-08-09
 1    1     S  2020-12-08
 2    2     A  2021-05-30
 3    3     A  2018-03-26
 4    3     S  2020-12-08
 5    4     A  2022-05-02
 6    5     A  2019-11-05
 7    5     S  2022-04-25
 8    6     A  2022-03-03
 9    7     A  2017-03-29
 10   7     S  2018-05-02
 11   7     M  2021-09-01
 12   8     A  2018-11-26
 13   8     S  2020-03-15
 14   8     M  2022-05-03,
 'staff_samecol_df':    ID   Name  DeptId  Age Gender  Salary  UpdateDate
 0   1   Mike       2   45      M   60000  2020-12-08
 1   2   Judy       2   30      F   48000  2021-05-30
 2   3  Allen       1   22      M   50000  2020-12-08
 3   4    Tom       2   47      M   47000  2022-05-02
 4   5   Jack       3   36      M   52000  2022-04-25
 5   6   Abby       2   24      F   45000  2022-03-03
 6   7  Trump       1   80      M   80000  2021-09-01
 7   8  Marry       3   29      F   87000  2022-05-03,
 'staff_df':    ID   Name  DeptId  Age Gender  Salary
 0   1   Mike       2   45      M   60000
 1   2   Judy       2   30      F   48000
 2   3  Allen       1   22      M   50000
 3   4    Tom       2   47      M   47000
 4   5   Jack       3   36      M   52000
 5   6   Abby       2   24      F   45000
 6   7  Trump       1   80      M   80000
 7   8  Marry       3   29      F   87000,
 '_i2': 'import duckdb\n\ncon = duckdb.connect()\n\n# 讀 parquet 檔\ndf = con.execute("""\n    SELECT *\n    FROM \'staff_df\'\n""").fetchdf()\n\ndf',
 'duckdb': <module 'duckdb' from '/Users/uuboy.scy/Library/Caches/pypoetry/virtualenvs/data-pipeline-fKJzP9fV-py3.12/lib/python3.12/site-packages/duckdb/__init__.py'>,
 'con': <_duckdb.DuckDBPyConnection at 0x108ec6a30>,
 'df':    ID   Name  DeptId  Age Gender  Salary
 0   1   Mike       2   45      M   60000
 1   2   Judy       2   30      F   48000
 2   3  Allen       1   22      M   50000
 3   4    Tom       2   47      M   47000
 4   5   Jack       3   36      M   52000
 5   6   Abby       2   24      F   45000
 6   7  Trump       1   80      M   80000
 7   8  Marry       3   29      F   87000,
 '_2':    ID   Name  DeptId  Age Gender  Salary
 0   1   Mike       2   45      M   60000
 1   2   Judy       2   30      F   48000
 2   3  Allen       1   22      M   50000
 3   4    Tom       2   47      M   47000
 4   5   Jack       3   36      M   52000
 5   6   Abby       2   24      F   45000
 6   7  Trump       1   80      M   80000
 7   8  Marry       3   29      F   87000,
 '_i3': 'globals()'}

In [4]:
globals()["staff_df"]

   ID   Name  DeptId  Age Gender  Salary
0   1   Mike       2   45      M   60000
1   2   Judy       2   30      F   48000
2   3  Allen       1   22      M   50000
3   4    Tom       2   47      M   47000
4   5   Jack       3   36      M   52000
5   6   Abby       2   24      F   45000
6   7  Trump       1   80      M   80000
7   8  Marry       3   29      F   87000

In [5]:
locals()

{'__name__': '__main__',
 '__doc__': 'Automatically created module for IPython interactive environment',
 '__package__': None,
 '__loader__': None,
 '__spec__': None,
 '__builtin__': <module 'builtins' (built-in)>,
 '__builtins__': <module 'builtins' (built-in)>,
 '_ih': ['',
  'import pandas as pd\n\nstaff_detail_different_col_path = "staff_detail_different_col.csv"\nstaff_detail_path = "staff_detail.csv"\nstaff_samecol_path = "staff_samecol.csv"\nstaff_path = "staff.csv"\n\nstaff_detail_different_col_df = pd.read_csv(staff_detail_different_col_path)\nstaff_detail_df = pd.read_csv(staff_detail_path)\nstaff_samecol_df = pd.read_csv(staff_samecol_path)\nstaff_df = pd.read_csv(staff_path)',
  'import duckdb\n\ncon = duckdb.connect()\n\n# 讀 parquet 檔\ndf = con.execute("""\n    SELECT *\n    FROM \'staff_df\'\n""").fetchdf()\n\ndf',
  'globals()',
  'globals()["staff_df"]',
  'locals()'],
 '_oh': {2:    ID   Name  DeptId  Age Gender  Salary
  0   1   Mike       2   45      M   60000
  1   2   Judy       2   30      F   48000
  2   3  Allen       1   22      M   50000
  3   4    Tom       2   47      M   47000
  4   5   Jack       3   36      M   52000
  5   6   Abby       2   24      F   45000
  6   7  Trump       1   80      M   80000
  7   8  Marry       3   29      F   87000,
  3: {...},
  4:    ID   Name  DeptId  Age Gender  Salary
  0   1   Mike       2   45      M   60000
  1   2   Judy       2   30      F   48000
  2   3  Allen       1   22      M   50000
  3   4    Tom       2   47      M   47000
  4   5   Jack       3   36      M   52000
  5   6   Abby       2   24      F   45000
  6   7  Trump       1   80      M   80000
  7   8  Marry       3   29      F   87000},
 '_dh': [PosixPath('/Users/uuboy.scy/side-project/tibame/tjr104/data-pipeline')],
 'In': ['',
  'import pandas as pd\n\nstaff_detail_different_col_path = "staff_detail_different_col.csv"\nstaff_detail_path = "staff_detail.csv"\nstaff_samecol_path = "staff_samecol.csv"\nstaff_path = "staff.csv"\n\nstaff_detail_different_col_df = pd.read_csv(staff_detail_different_col_path)\nstaff_detail_df = pd.read_csv(staff_detail_path)\nstaff_samecol_df = pd.read_csv(staff_samecol_path)\nstaff_df = pd.read_csv(staff_path)',
  'import duckdb\n\ncon = duckdb.connect()\n\n# 讀 parquet 檔\ndf = con.execute("""\n    SELECT *\n    FROM \'staff_df\'\n""").fetchdf()\n\ndf',
  'globals()',
  'globals()["staff_df"]',
  'locals()'],
 'Out': {2:    ID   Name  DeptId  Age Gender  Salary
  0   1   Mike       2   45      M   60000
  1   2   Judy       2   30      F   48000
  2   3  Allen       1   22      M   50000
  3   4    Tom       2   47      M   47000
  4   5   Jack       3   36      M   52000
  5   6   Abby       2   24      F   45000
  6   7  Trump       1   80      M   80000
  7   8  Marry       3   29      F   87000,
  3: {...},
  4:    ID   Name  DeptId  Age Gender  Salary
  0   1   Mike       2   45      M   60000
  1   2   Judy       2   30      F   48000
  2   3  Allen       1   22      M   50000
  3   4    Tom       2   47      M   47000
  4   5   Jack       3   36      M   52000
  5   6   Abby       2   24      F   45000
  6   7  Trump       1   80      M   80000
  7   8  Marry       3   29      F   87000},
 'get_ipython': <bound method InteractiveShell.get_ipython of <ipykernel.zmqshell.ZMQInteractiveShell object at 0x108bbd130>>,
 'exit': <IPython.core.autocall.ZMQExitAutocall at 0x1080ef080>,
 'quit': <IPython.core.autocall.ZMQExitAutocall at 0x1080ef080>,
 'open': <function _io.open(file, mode='r', buffering=-1, encoding=None, errors=None, newline=None, closefd=True, opener=None)>,
 '_':    ID   Name  DeptId  Age Gender  Salary
 0   1   Mike       2   45      M   60000
 1   2   Judy       2   30      F   48000
 2   3  Allen       1   22      M   50000
 3   4    Tom       2   47      M   47000
 4   5   Jack       3   36      M   52000
 5   6   Abby       2   24      F   45000
 6   7  Trump       1   80      M   80000
 7   8  Marry       3   29      F   87000,
 '__': {...},
 '___':    ID   Name  DeptId  Age Gender  Salary
 0   1   Mike       2   45      M   60000
 1   2   Judy       2   30      F   48000
 2   3  Allen       1   22      M   50000
 3   4    Tom       2   47      M   47000
 4   5   Jack       3   36      M   52000
 5   6   Abby       2   24      F   45000
 6   7  Trump       1   80      M   80000
 7   8  Marry       3   29      F   87000,
 '__vsc_ipynb_file__': '/Users/uuboy.scy/side-project/tibame/tjr104/data-pipeline/10_duckdb.ipynb',
 '_i': 'globals()["staff_df"]',
 '_ii': 'globals()',
 '_iii': 'import duckdb\n\ncon = duckdb.connect()\n\n# 讀 parquet 檔\ndf = con.execute("""\n    SELECT *\n    FROM \'staff_df\'\n""").fetchdf()\n\ndf',
 '_i1': 'import pandas as pd\n\nstaff_detail_different_col_path = "staff_detail_different_col.csv"\nstaff_detail_path = "staff_detail.csv"\nstaff_samecol_path = "staff_samecol.csv"\nstaff_path = "staff.csv"\n\nstaff_detail_different_col_df = pd.read_csv(staff_detail_different_col_path)\nstaff_detail_df = pd.read_csv(staff_detail_path)\nstaff_samecol_df = pd.read_csv(staff_samecol_path)\nstaff_df = pd.read_csv(staff_path)',
 'pd': <module 'pandas' from '/Users/uuboy.scy/Library/Caches/pypoetry/virtualenvs/data-pipeline-fKJzP9fV-py3.12/lib/python3.12/site-packages/pandas/__init__.py'>,
 'staff_detail_different_col_path': 'staff_detail_different_col.csv',
 'staff_detail_path': 'staff_detail.csv',
 'staff_samecol_path': 'staff_samecol.csv',
 'staff_path': 'staff.csv',
 'staff_detail_different_col_df':     EmpNum Level  UpdateDate
 0        1     A  2019-08-09
 1        1     S  2020-12-08
 2        2     A  2021-05-30
 3        3     A  2018-03-26
 4        3     S  2020-12-08
 5        4     A  2022-05-02
 6        5     A  2019-11-05
 7        5     S  2022-04-25
 8        6     A  2022-03-03
 9        7     A  2017-03-29
 10       7     S  2018-05-02
 11       7     M  2021-09-01
 12       8     A  2018-11-26
 13       8     S  2020-03-15
 14       8     M  2022-05-03,
 'staff_detail_df':     ID Level  UpdateDate
 0    1     A  2019-08-09
 1    1     S  2020-12-08
 2    2     A  2021-05-30
 3    3     A  2018-03-26
 4    3     S  2020-12-08
 5    4     A  2022-05-02
 6    5     A  2019-11-05
 7    5     S  2022-04-25
 8    6     A  2022-03-03
 9    7     A  2017-03-29
 10   7     S  2018-05-02
 11   7     M  2021-09-01
 12   8     A  2018-11-26
 13   8     S  2020-03-15
 14   8     M  2022-05-03,
 'staff_samecol_df':    ID   Name  DeptId  Age Gender  Salary  UpdateDate
 0   1   Mike       2   45      M   60000  2020-12-08
 1   2   Judy       2   30      F   48000  2021-05-30
 2   3  Allen       1   22      M   50000  2020-12-08
 3   4    Tom       2   47      M   47000  2022-05-02
 4   5   Jack       3   36      M   52000  2022-04-25
 5   6   Abby       2   24      F   45000  2022-03-03
 6   7  Trump       1   80      M   80000  2021-09-01
 7   8  Marry       3   29      F   87000  2022-05-03,
 'staff_df':    ID   Name  DeptId  Age Gender  Salary
 0   1   Mike       2   45      M   60000
 1   2   Judy       2   30      F   48000
 2   3  Allen       1   22      M   50000
 3   4    Tom       2   47      M   47000
 4   5   Jack       3   36      M   52000
 5   6   Abby       2   24      F   45000
 6   7  Trump       1   80      M   80000
 7   8  Marry       3   29      F   87000,
 '_i2': 'import duckdb\n\ncon = duckdb.connect()\n\n# 讀 parquet 檔\ndf = con.execute("""\n    SELECT *\n    FROM \'staff_df\'\n""").fetchdf()\n\ndf',
 'duckdb': <module 'duckdb' from '/Users/uuboy.scy/Library/Caches/pypoetry/virtualenvs/data-pipeline-fKJzP9fV-py3.12/lib/python3.12/site-packages/duckdb/__init__.py'>,
 'con': <_duckdb.DuckDBPyConnection at 0x108ec6a30>,
 'df':    ID   Name  DeptId  Age Gender  Salary
 0   1   Mike       2   45      M   60000
 1   2   Judy       2   30      F   48000
 2   3  Allen       1   22      M   50000
 3   4    Tom       2   47      M   47000
 4   5   Jack       3   36      M   52000
 5   6   Abby       2   24      F   45000
 6   7  Trump       1   80      M   80000
 7   8  Marry       3   29      F   87000,
 '_2':    ID   Name  DeptId  Age Gender  Salary
 0   1   Mike       2   45      M   60000
 1   2   Judy       2   30      F   48000
 2   3  Allen       1   22      M   50000
 3   4    Tom       2   47      M   47000
 4   5   Jack       3   36      M   52000
 5   6   Abby       2   24      F   45000
 6   7  Trump       1   80      M   80000
 7   8  Marry       3   29      F   87000,
 '_i3': 'globals()',
 '_3': {...},
 '_i4': 'globals()["staff_df"]',
 '_4':    ID   Name  DeptId  Age Gender  Salary
 0   1   Mike       2   45      M   60000
 1   2   Judy       2   30      F   48000
 2   3  Allen       1   22      M   50000
 3   4    Tom       2   47      M   47000
 4   5   Jack       3   36      M   52000
 5   6   Abby       2   24      F   45000
 6   7  Trump       1   80      M   80000
 7   8  Marry       3   29      F   87000,
 '_i5': 'locals()'}